[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
first_solana_program = "A1N7F27c9hpCWRV4oGYShxn1UvVq1duyvQQZwFmWWpPH"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
