[package]
name = "task_03_create_transfer"
version = "0.1.0"
edition = "2021"

[dependencies]
solana-client = "1.14.14"
solana-sdk = "1.14.14"
anyhow = "1.0.68"
serde = { version = "1.0.164", features = ["derive"] }
serde_json = "1.0.99"